  admin-job-management[m
  admin-recruiter-sort[m
  baseRepoImpl[m
  candidate-education[m
  candidate-experience[m
  candidate-public-profile[m
* [32mfeat/features-tracking[m
  feature/ai-interview[m
  feature/chat[m
  feature/forgot-password[m
  feature/notification-alerts[m
  feed[m
  fix/cleanup[m
  fix/crashes[m
  improvement[m
  improvements-new[m
  job-details-users[m
  job-list-users[m
  main[m
  refactor/entity-refactor[m
  searchFeature[m
  temp/updates[m
  update/ai-resume[m
