export enum SocketEvents {
  FOLLOWED = 'FOLLOWED',
  CONNECTION_REQUEST = 'CONNECTION_REQUEST',
  CONNECTION_REQUEST_CANCELLED = 'CONNECTION_REQUEST_CANCELLED',
  CONNECTION_REQUEST_ACCEPTED = 'CONNECTION_REQUEST_ACCEPTED'
}
