export const EndPoints = {
    REGISTER: '/v1/user/register',
    VERIFY:  '/v1/user/verify',
    LOGIN:  '/v1/user/login',
    GOOGLE_LOGIN: `/v1/google/sign-up`,
    LOAD_USER_METADATA:  '/v1/user/me/metadata',
    RE_AUTHENTICATE:  '/v1/token/refresh',
    STORE_USER_BASIC_DETAILS:  '/v1/user/me/store-basics',
    MY_PROFILE:  '/v1/user/me',
    EDIT_PROFILE_DETAILS: '/v1/user/me',
    ADD_SOCIAL_MEDIA_LINKS:  '/v1/user/me/social-links',
    REMOVE_SOCIAL_MEDIA_LINKS: '/v1/user/me/social-links/remove',
    GET_MY_RESUMES:  '/v1/user/me/resumes',
    GET_MY_CERTIFICATES:  '/v1/user/me/certificates',
    ADD_CERTIFICATE:  '/v1/user/me/certificate/add',
    DELETE_CERTIFICATE:  (certificateId: string) => `/v1/user/me/certificate/${certificateId}`,
    ADD_RESUME: '/v1/user/me/resume',
    DELETE_RESUME: (resumeId: string) => `/v1/user/me/resume/${resumeId}`,
    SET_RESUME_PRIMARY: (resumeId: string) => `/v1/user/me/resume/${resumeId}/set-primary`,
    GET_EXPERIENCES: '/v1/user/me/experiences',
    ADD_EXPERIENCE: '/v1/user/me/experience',
    EDIT_EXPERIENCE: (experienceId: string) => `/v1/user/me/experience/${experienceId}`,
    DELETE_EXPERIENCE: (experienceId: string) => `/v1/user/me/experience/${experienceId}`,
    GET_EDUCATIONS: '/v1/user/me/educations',
    ADD_EDUCATION: '/v1/user/me/education',
    EDIT_EDUCATION: (educationId: string) => `/v1/user/me/education/${educationId}`,
    DELETE_EDUCATION: (educationId: string) => `/v1/user/me/education/${educationId}`,
    GET_SKILLS: `/v1/user/me/skills`,
    ADD_SKILL: `/v1/user/me/skill`,
    DELETE_SKILL: (skillId: string) => `/v1/user/me/skills/${skillId}`,
    CREATE_FEED_POST: '/v1/post',
    GET_FEED_POSTS: '/v1/posts',
    LIKE_FEED_POST: (postId: string) => `/v1/post/like/${postId}`,
    UNLIKE_FEED_POST: (postId: string) => `/v1/post/unlike/${postId}`,
    COMMENT_FEED_POST: (postId: string) => `/v1/post/${postId}/comment`,
    DELETE_COMMENT: (postId: string, commentId: string) => `/v1/post/${postId}/comment/${commentId}`,
    LIKE_COMMENT: (commentId: string) => `/v1/post/comment/${commentId}`,
    UNLIKE_COMMENT: (commentId: string) => `/v1/post/comment/${commentId}/unlike`,
    DELETE_POST: (postId: string) => `/v1/post/${postId}`,
    HIDE_POST: (postId: string) => `/v1/posts/${postId}/hide`,
    UNHIDE_POST: (postId: string) => `/v1/posts/${postId}/unhide`,
    SAVE_POST: (postId: string) => `/v1/posts/${postId}/save`,
    GET_USERS: `/v1/users`,
    GET_NOTIFICATIONS: `/v1/notifications`,
    MARK_ALL_NOTIFICATIONS_READ: '/v1/notifications/mark-all-read',
    GET_UNREAD_NOTIFICATIONS_COUNT: '/v1/notifications/unread-count',
    DELETE_NOTIFICATION: `/v1/notifications/delete`,
    FOLLOW_A_USER: (id: string) =>  `/v1/user/follow/${id}`,
    UNFOLLOW_A_USER: (id: string) => `/v1/user/unfollow/${id}`,
    SEND_CONNECTION_REQUEST: (receiverId: string) =>  `/v1/user/connect-request/${receiverId}`,
    CANCEL_CONNECTION_REQUEST: (receiverId: string) => `/v1/user/connection-request-cancel/${receiverId}`,
    REJECT_CONNECTION_REQUEST: `/v1/user/connection-request-reject`,
    ACCEPT_CONNECTION_REQUEST: `/v1/user/connection-request-accept/`,

    APPLY_JOB_BY_JOB_ID: (jobId: string) => `/v1/job/${jobId}/apply`,
    GET_MY_INTERVIEWS: '/v1/interviews',
    CHECK_IS_JOB_APPLIED: (jobId: string) => `/v1/job/${jobId}/applied`,
    CHECK_IS_JOB_SAVED: (jobId: string) => `/v1/job/${jobId}/saved/check`,
    SAVE_JOB: (jobId: string) => `/v1/job/${jobId}/save`,
    UNSAVE_JOB: (savedId: string) => `/v1/job/${savedId}/unsave`,
    LOAD_SAVED_JOBS: '/v1/job/saved',
    LOAD_MY_APPLICATIONS: '/v1/applications',
    TRACK_MY_APPLICATION: (applicationId: string) => `/v1/application/${applicationId}/track`,
    UPLOAD_PROFILE_PICTURE: '/v1/user/me/profile-picture',
    REMOVE_PROFILE_PICTURE: `/v1/user/me/profile-picture/remove`,
    UPLOAD_COVER_PHOTO: '/v1/user/me/cover-photo',
    REMOVE_COVER_PHOTO: '/v1/user/me/cover-photo/remove',
    WITHDRAW_APPLICATION: (applicationId: string) => `/v1/application/${applicationId}`,

    LOAD_ALL_USERS: '/v2/users',
    LOAD_USER_DETAIL_BY_ID: (userId: string) => `/v2/users/details/${userId}`,
    BLOCK_USER_BY_ID: (userId: string) => `/v2/user/block/${userId}`,
    UNBLOCK_USER_BY_ID: (userId: string) => `/v2/user/unblock/${userId}`,
    DELETE_USER_BY_ID: (userId: string) => `/v2/user/${userId}`,
    BAN_USER_BY_ID: (userId: string) => `/v2/user/ban/${userId}`,

    USER_PROFILE_VIEWED: (profileId: string) => `/v2/user/profile/${profileId}/viewed`,

    LOAD_USER_FULL_PROFILE_DETAILS: '/v2/user/full-profile/details',
    START_AI_INTERVIEW: '/v2/interview/ai',
    LOAD_DASHBOARD: '/v2/interview/ai/dashboard',

    VALIDATE_TOKEN: '/v1/token-verify'
} as const