import JobAggregatedDTO from '../../application/DTOs/job/jobDetails.dto.FIX';
import JobAggregated from '../entities/jobAggregated.entity';

export default function mapJobAggregatedToJobDetailsDTO(
  jobAggregated: JobAggregated
): JobAggregatedDTO {
  return {
    _id: jobAggregated._id,
    description: jobAggregated.description,
    duration: jobAggregated.duration,
    experienceInYears: jobAggregated.experienceInYears,
    jobLevel: jobAggregated.jobLevel,
    jobTitle: jobAggregated.jobTitle,
    jobType: jobAggregated.jobType,
    location: jobAggregated.location,
    maxSalary: jobAggregated.maxSalary,
    minSalary: jobAggregated.minSalary,
    optionalSkills: jobAggregated.optionalSkills,
    qualification: jobAggregated.qualification,
    requiredSkills: jobAggregated.requiredSkills,
    requirements: jobAggregated.requirements,
    responsibilities: jobAggregated.responsibilities,
    vacancies: jobAggregated.vacancies,
    recruiterId: jobAggregated.recruiterId,
    createdAt: jobAggregated.createdAt,
    updatedAt: jobAggregated.updatedAt,
    status: jobAggregated.status,
    salaryCurrency: jobAggregated.salaryCurrency,
    salaryPeriod: jobAggregated.salaryPeriod,
    workMode: jobAggregated.workMode,
    expiresAt: jobAggregated.expiresAt as string,
    rejectionReason: jobAggregated.rejectionReason,
    applicationsCount: jobAggregated.applicationsCount,
    views: jobAggregated.views,
    userProfile: jobAggregated.userProfile,
    userRecruiterProfile: jobAggregated.userRecruiterProfile,
    candidateIds: jobAggregated.candidateIds,
    // _id: jobAggregated._id,
    // companyDetails: jobAggregated.companyDetails,
    // description: jobAggregated.description,
    // duration: jobAggregated.duration,
    // experience: jobAggregated.experience,
    // expiresAt: jobAggregated.experience,
    // jobLevel: jobAggregated.jobLevel,
    // jobTitle: jobAggregated.jobTitle,
    // jobType: jobAggregated.jobType,
    // location: jobAggregated.location,
    // locationType: jobAggregated.locationType,
    // maxSalary: jobAggregated.maxSalary,
    // minSalary: jobAggregated.minSalary,
    // optionalSkills: jobAggregated.optionalSkills,
    // qualification: jobAggregated.qualification,
    // requiredSkills: jobAggregated.requiredSkills,
    // requirements: jobAggregated.requirements,
    // responsibilities: jobAggregated.responsibilities,
    // vacancies: jobAggregated.vacancies,
    // companyId: jobAggregated.companyId,
    // createdAt: jobAggregated.createdAt,
    // isBlocked: jobAggregated.isBlocked,
    // isRejected: jobAggregated.isRejected,
    // updatedAt: jobAggregated.updatedAt,
    // experienceInYears: jobAggregated.experienceInYears,
    // status: jobAggregated.status,
    // rejectionReason: jobAggregated.rejectionReason,
    // views: jobAggregated.views,
    // applicationsCount: jobAggregated.applicationsCount,
    // userDetails: jobAggregated.userDetails,
    // recruiterProfile: jobAggregated.recruiterProfile,
    // workMode: jobAggregated.workMode,
  };
}
