enum SocketEvents {
    //chat events
    JOIN_ROOM = 'JOIN_ROOM',
    SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE',
    RECEIVE_PRIVATE_MESSAGE = 'RECEIVE_PRIVATE_MESSAGE',
    MARK_MESSAGE_AS_READ = 'MARK_MESSAGE_AS_READ',
    MESSAGE_READ_UPDATE = 'MESSAGE_READ_UPDATE',
    USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',

    //user events
    CONNECTION_REQUEST = 'CONNECTION_REQUEST_RECEIVED',
    CONNECTION_ACCEPTED = 'CONNECTION_REQUEST_ACCEPTED',
    CONNECTION_REJECTED = 'CONNECTION_REQUEST_REJECTED',
    CONNECTION_CANCELED = 'CONNECTION_REQUEST_CANCELED',
    FOLLOWED = 'FOLLOWED',
    UNFOLLOWED = 'UNFOLLOWED',
    
    //post events
    FEED_POST_LIKED = 'FEED_POST_LIKED',
    MY_POST_LIKED = 'MY_POST_LIKED',
    FEED_POST_UNLIKED = 'FEED_POST_UNLIKED',
    MY_POST_UNLIKED = 'MY_POST_UNLIKED',
    FEED_POST_COMMENTED = 'FEED_POST_COMMENTED',
    MY_POST_COMMENTED = 'MY_POST_COMMENTED',
    FEED_POST_COMMENT_REMOVED = 'FEED_POST_COMMENT_REMOVED',
    MY_POST_COMMENT_REMOVED = 'MY_POST_COMMENT_REMOVED'
}